config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'hackathons#index'

  resources :hackathons, only: [:index, :show]
  resources :rsvps, only: [:create, :destroy]

  get '/account' => 'users#account', as: :account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hackathon.rb
class Hackathon < ApplicationRecord
  has_many :rsvps
  has_many :attendees, through: :rsvps, source: :attendee
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  attr_accessor :referral_code

  belongs_to :hackathon
  belongs_to :attendee,
             :class_name => 'User',
             :foreign_key => 'user_id'
  belongs_to :referred_by,
             :class_name  => "User",
             :foreign_key => 'referred_by_user_id',
             :optional    => true

  validate :ensure_valid_referral_code, if: :referral_present?
  before_create :set_referred_by_user, if: :referral_present?

  private

  def ensure_valid_referral_code
    if self_referral?
      errors.add(:referral_code, 'cannot be your own.')
    elsif !referral_exists?
      errors.add(:referral_code, 'is invalid, please verify and try again.')
    end
  end

  def referral_present?
    !referral_code.blank?
  end

  def referral_exists?
    User.find_by(referral_code: referral_code)
  end

  def self_referral?
    attendee.referral_code == referral_code
  end

  def set_referred_by_user
    self.referred_by = User.find_by(referral_code: referral_code)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable

  has_many :rsvps

  before_create :set_referral_code

  private

  def generate_referral_code
    Digest::SHA1.hexdigest([ id, Time.now ].join)[0..5]
  end

  def set_referral_code
    self.referral_code = generate_referral_code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hackathons_controller.rb
class HackathonsController < ApplicationController
  before_filter :set_rsvp, only: :show

  def index
    @hackathons = Hackathon.all
  end

  def show
    @hackathon = Hackathon.includes(:attendees).find(params[:id])
  end

  private

  def set_rsvp
    @rsvp =
      Rsvp.where("user_id = ? AND hackathon_id = ?", current_user, params[:id]).first
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  def create
    rsvp = current_user.rsvps.new(create_params)

    if rsvp.save
      redirect_to hackathon_path(rsvp.hackathon_id)
    else
      redirect_to hackathon_path(rsvp.hackathon_id),
        :flash => { :error => rsvp.errors.full_messages.first }
    end
  end

  def destroy
    rsvp = Rsvp.find(params[:id])

    if rsvp.destroy
      redirect_to hackathon_path(rsvp.hackathon_id)
    end
  end

  private

  def create_params
    params.require(:rsvp).permit(:hackathon_id, :referral_code)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :referred_users

  def account
  end

  private

  def referred_users
    @referred_users ||=
      Rsvp.includes(:attendee, :hackathon).where(referred_by: current_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hackathons/_attendees.html.erb
<% if attendees.any? %>
  <!-- <p> <%= attendees.size %> hackers attending </p> -->
  <% attendees.each do |attendee| %>
  <%= fa_icon "user-circle", class: "fa-2x" %>
  <% end %>
<% else %>
  <p> No current registrants for this event. You could be the first! </p>
<% end %>

app/views/hackathons/index.html.erb
<div class="row">
  <h1>Upcoming Hackathons</h1>

  <% @hackathons.each do |hackathon| %>
    <div class="hackthon--block col-sm-4">
      <a href="<%= hackathon_path(hackathon) %>">
        <img class="hackathon_cover_img" src="<%= hackathon.cover_image_url %>" />
    </div>
  <% end %>
</div>

app/views/hackathons/show.html.erb
<div class="row">
  <div class="col-sm-2"></div>

  <div class="col-sm-6">
    <% if flash[:error] %>
    <div class="alert alert-danger alert-dismissable">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= flash[:error] %>
    </div>

    <% end %>
    <h2><%= @hackathon.title %></h2>
    <hr />
    <p><%= @hackathon.description %></p>
  </div>

  <div class="col-sm-2">
    <div class="hackathon_details--item">
      <h3>rsvp</h3>
      <hr />
      <% if current_user %>
        <% if @rsvp %>
          <%= render partial: "rsvps/edit", locals: { rsvp: @rsvp } %>
        <% else %>
          <%= render partial: "rsvps/new", locals: { hackathon_id: @hackathon.id} %>
        <% end %>
      <% else %>
        <p>You must be a registered user in order to rsvp for an event.</p>
      <% end %>
    </div>

    <% if current_user %>
      <div class="hackathon_details--item">
        <h3>referrals</h3>
        <hr />
        <p>
          Refer a friend and earn rewards for future events, with the following
          referral code: <strong><%= current_user.referral_code %></strong>.
        </p>
      </div>
    <% end %>

    <div class="hackathon_details--item">
      <h3>attendees</h3>
      <hr />
      <% if @hackathon.attendees.any? %>
        <%= render partial: "attendees", locals: { attendees: @hackathon.attendees } %>
      <% else %>
        <p> No attendees yet, be the first!
      <% end %>
    </div>
  </div>

  <div class="col-sm-2"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MLH</title>
    <meta name="viewport" content="initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/header" %>
    <main class="container-fluid">
      <%= yield %>
    </main>
  </body>
</html>

app/views/rsvps/_edit.html.erb
<p> You're currently RSVP'd for this event.</p>

<%= button_to "Cancel RSVP", rsvp_path(@rsvp), method: :delete, class: "btn btn-warning"%>

app/views/rsvps/_new.html.erb
<%= form_for :rsvp, url: rsvps_path do |f| %>
  <%= f.hidden_field :hackathon_id, value: hackathon_id %>
  <%= f.label :referral_code, "Have a referral code? (optional)", class: "control-label" %>
  <%= f.text_field :referral_code, value: params[:referral_code], class: "form-control" %>
  <%= f.submit "RSVP", class: "btn btn-success" %>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="col-sm-1"></div>
  <div class="col-sm-5">
    <%= image_tag "logo.svg", class: "logo" %>
  </div>

  <div class="col-sm-5">
    <!-- <% if current_user %>
      <p> Hi <%= current_user.email %> </p>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
    <% end %> -->

    <nav>
      <ul>
        <li><a href="<%= hackathons_path %>">Hackathons</a></li>
        <% if current_user %>
          <li><a href="<%= account_path %>">My Account</a></li>
          <li><%= link_to "Log out", destroy_user_session_path, :method=> :delete %></li>
        <% else %>
          <li><a href="<%= new_user_session_path %>">Log In</a></li>
          <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/users/_referred_users_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Event</th>
      <th>User</th>
      <th>Referred on</th>
    </tr>
  </thead>
  <tbody>
    <% counter = 0 %>
    <% referred_users.each do |r| %>
      <% counter += 1 %>
      <tr>
        <th scope="row"><%= counter %></th>
        <td> <%= r.hackathon.title %> </td>
        <td> <%= r.attendee.email  %> </td>
        <td> <%= r.created_at %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/account.html.erb
<div class="row">
  <h1>My Account</h1>

  <div class="col-sm-3"></div>

  <div class="col-sm-6">
    <p>
      Refer a friend and earn rewards for future events, with the following
      referral code: <strong><%= current_user.referral_code %></strong>.
    </p>
    <hr />

    <% if @referred_users.any? %>
      <%= render partial: "referred_users_table", locals: { referred_users: @referred_users} %>

    <% else %>
      <p> Looks like you haven't referred anyone yet!
    <% end %>
  </div>

  <div class="col-sm-3"></div>
</div>